### ISSUE TITLE
如何貢獻

### ISSUE THREAD

**Issue by racketprogram** [yisar/joke#1]
嗨你願意寫一下你的設計思路嗎

我也有興趣同時學 rust 跟 js

**Comment by yisar** [comment]
https://zhuanlan.zhihu.com/p/143331414
这里有一篇文章
因为还只是刚开始，所以目前仅仅是能跑通

**Comment by racketprogram** [comment]
好的 這篇文章我其實有看 那我看能不能寫個測試好了
